### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by bachoo786** [sdetweil/MagicMirror_scripts#33]
Hi 

I have used your script to install MM on my pi4 and I have followed all the other scripts and have disabled screen blanking etc. However I noticed that after a few hours MM goes blank and doesn't respond. When I check pm2 it shows that it's still running. 

So I tried to stop running MM by doing pm2 stop MagicMirror and it does stop but takes a while and also to start it again it takes much longer until I have to restart my pi 4.

I have connect my pi4 via ethernet so it's not ineternet issue.

Any ideas?

PS. It's a fresh raspbian buster installation installed via the raspbian imager software on Windows.

**Comment by sdetweil** [comment]
u should turn off screen blanking in the raspi config.  this is different from screen saver

**Comment by bachoo786** [comment]
I have turned it off. It's something to do with pm2 as it becomes really slow to turn MM off or even on it.

**Comment by sdetweil** [comment]
what pi is this? 

pm2 just starts/stops. 
it doesn't know what it is..

**Comment by bachoo786** [comment]
It's a pi4

**Comment by bachoo786** [comment]
> what pi is this?
> 
> pm2 just starts/stops.
> it doesn't know what it is..

so I checked my pm2 log and there are some errors, I have posted them below:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.14
3 info using node@v14.17.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.16.0~prestart: magicmirror@2.16.0
6 info lifecycle magicmirror@2.16.0~start: magicmirror@2.16.0
7 verbose lifecycle magicmirror@2.16.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle magicmirror@2.16.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/$
9 verbose lifecycle magicmirror@2.16.0~start: CWD: /home/pi/MagicMirror
10 silly lifecycle magicmirror@2.16.0~start: Args: [ '-c', './run-start.sh $1' ]
11 silly lifecycle magicmirror@2.16.0~start: Returned: code: 1  signal: null
12 info lifecycle magicmirror@2.16.0~start: Failed to exec start script
13 verbose stack Error: magicmirror@2.16.0 start: `./run-start.sh $1`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid magicmirror@2.16.0
15 verbose cwd /home/pi/MagicMirror
16 verbose Linux 5.10.52-v7l+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v14.17.4
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error magicmirror@2.16.0 start: `./run-start.sh $1`
22 error Exit status 1
23 error Failed at the magicmirror@2.16.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Can you help please?

**Comment by sdetweil** [comment]
I am away until sometime tomorrow

**Comment by sdetweil** [comment]
the only other thing is to disable one module at a time and see if u can find which one is having trouble

**Comment by sdetweil** [comment]
did u solve this?

**Comment by bachoo786** [comment]
Yes I had to reinstall raspbian buster and MM. Seems to be working fine now.
